### ISSUE TITLE
About the fitness file

### ISSUE THREAD

**Issue by Aaronro16** [niklases/PyPEF#1]
Hi,

I'm interested to use this in another protein, but I don't know how to obtain the VARIANT-FITNESS-ENCODING_DATA.CSV file... How can obtain it for any protein?

Ty

**Comment by niklases** [comment]
> Hi,
> 
> 
> 
> I'm interested to use this in another protein, but I don't know how to obtain the VARIANT-FITNESS-ENCODING_DATA.CSV file... How can obtain it for any protein?
> 
> 
> 
> Ty

Hi,

the presented framework is a supervised method, so the variant (sequences) and the corresponding fitness values are always required for model training (and testing). If you have these (e.g. collected from lab/literature) you can encode the given variants/sequences using the 'pypef encode' function. 
If you don't have these collected, you have to stick to an unsupervised protein fitness prediction method (e.g. EVcouplings/EVmutation). 

Hope this helps!

**Comment by Aaronro16** [comment]
Hi thanks for your reply,

But I was wrong, I meant how can I obtain the file VARIANT-FITNESS_DATA.CSV??

Cause I kow which residues of the protein I want to mutate and tets.

Thanks again.

**Comment by niklases** [comment]
Welcome,

for generating the encoded variant-fitness CSV file you can use the 'encode' function on your input variant-Fitness CSV, e.g.

pypef encode -e onehot -i avGFP.csv -w P42212_F64L.fasta

for one-hot encoding or 

pypef encode -e dca -i avGFP.csv -w P42212_F64L.fasta --params uref100_avgfp.params

as example for DCA-based encoding. 

Also see https://github.com/niklases/PyPEF/blob/main/workflow/Workflow_PyPEF.ipynb for further potentially helpful descriptions of available functions and commands.

**Comment by Aaronro16** [comment]
Hi, 

Sorry but for me isn't clear how do you obtain the columns ddG or E-value from 37_ANEH_variants.csv or fitness column of avGFP.csv.

Thanks again.

**Comment by niklases** [comment]
Hi,

these are (relative) variant fitness values collected from literature, i.e. wet-lab measured fitness values a.k.a. true/measured fitness labels.
These are required for supervised model training - and testing. If you don't have these values available from literature respectively wet-lab, then an unsupervised method has to be used.
