### ISSUE TITLE
Where is the workflow folder?

### ISSUE THREAD

**Issue by Qianyue-Wang** [niklases/PyPEF#3]
After installing jupyter kernel ,The tutorial shows to "cd workflow",but I can not find 'workflow' folder.
So ,where is the workflow folder?

**Comment by Qianyue-Wang** [comment]
![屏幕截图 2023-11-09 123725](https://github.com/niklases/PyPEF/assets/98954008/53decbae-b825-4f0b-aff0-8c0f7aa20ec6)
above is the install condition of my jupyter.

**Comment by niklases** [comment]
Hi,
unfortunately I missed that during last code/folder structure refactoring. The workflow folder directory (including the Workflow notebook) changed to /scripts/CLI. I changed the `README.md` accordingly. Thanks for raising this issue.
