### ISSUE TITLE
How to　reproduce the results in the paper

### ISSUE THREAD

**Issue by Qianyue-Wang** [niklases/PyPEF#5]
Hi,
When I used instruction "python...  /.. /pypef/main.py ml -e aaidx -l LS.fasl -t TS.fasl --regressor pls  --save 533“ to reproduce the results of Fig．2 of   the paper, I found that the value of R2 in the saved evaluation file (Model_results.txt) was abnormal,  reaching 0.9. Could you please tell me whether the instructions I run wasright? How to reproduce the experimental results in Figure 2 of the paper? (dataset　is　ANEN)

**Comment by Qianyue-Wang** [comment]
![捕获](https://github.com/niklases/PyPEF/assets/98954008/bccade4a-270f-4c26-9525-449bd21c1ed8)

**Comment by Qianyue-Wang** [comment]
This is the result saved on PLS, I replaced some of the evaluation metrics, but did not make any changes to the calculation of R2. From the preserved results, R2 and MSE are seriously inconsistent with the original paper.

**Comment by niklases** [comment]
Hi,
to reproduce the results, you have to create the training and testing files according to the described split of variant-fitness data. To reproduce results for Dataset B, you can simply run 
`%run ../../pypef/main.py ml -e aaidx -l LS_B.fasl -t TS_B.fasl --regressor pls` as LS_B.fasl and TS_B.fasl are provided in the ANEH folder as example data.

**Comment by Qianyue-Wang** [comment]
Thanks a lot :)

**Comment by niklases** [comment]
By the way, the used dataset files A-D for PyPEF are available in the SI files of the manuscript (https://ndownloader.figstatic.com/collections/5512280/versions/1). More datasets are e.g. available from https://github.com/Protein-Engineering-Framework/MERGE/tree/main/Data/_variant_fitness_wtseq.
